sonar.projectKey=devsecops-backend
sonar.projectName=VectorTech Backend
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.exclusions=**/target/**
