apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: devsecops
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/devsecops"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_SQL_INIT_PLATFORM: "postgres"
  SPRING_SQL_INIT_MODE: "never"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  REDIS_HOST: "redis-service"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  NEXT_PUBLIC_API_URL: "http://nginx-service"
