apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: devsecops
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
      tier: frontend
  template:
    metadata:
      labels:
        app: devsecops
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: devsecops-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: devsecops
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
      tier: backend
  template:
    metadata:
      labels:
        app: devsecops
        tier: backend
    spec:
      containers:
        - name: backend
          image: devsecops-backend:actuatorfix1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 30
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: devsecops
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
      tier: database
  template:
    metadata:
      labels:
        app: devsecops
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: devsecops
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: devsecops
    tier: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
      tier: cache
  template:
    metadata:
      labels:
        app: devsecops
        tier: cache
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: devsecops
    tier: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
      tier: proxy
  template:
    metadata:
      labels:
        app: devsecops
        tier: proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
